spring.main.banner-mode=off
spring.datasource.initialization-mode=always
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/insurance
spring.datasource.username=postgres
spring.datasource.password=postgres

#Postgres Driver
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=false
logging.level.root=INFO
log4j.config.file=log4j.properties
server.port=8092
server.servlet.context-path=/insurance-integration/

dummy.claimResponse.url=http://hapi.fhir.org/baseDstu3/ClaimResponse/1463597/_history/1?_format=json
dummy.eligibilityResponse.url=http://hl7.org/fhir/STU3/eligibilityresponse-example-benefits.json
dummy.claimTrack.url= http://hl7.org/fhir/STU3/task-example1.json

openmrs.odoo.api=http://192.168.33.20:8050/openmrs/ws/rest/v1/example/patient/
odoo.host=192.168.33.20
odoo.port=8069
odoo.database=odoo
odoo.user=admin
odoo.password=admin

imisconnect.user=admin
imisconnect.password=haha
imisconnect.errortrace.include=true
imisconnect.claimresource.save=true
imisconnect.eligresource.save=true

openimis.api.url=https://imislegacy.hib.gov.np/api/api_fhir/
openimis.api.user=testuser
openimis.api.password=f/\N6k@67
openimis.api.remote.user=hib_testuser_testfhir
openimis.enterer.id=7aa79c53-057e-4e77-8576-dfcfb03584a8
openimis.healthFacility.id=1ac457d3-efd3-4a67-89b3-bf8cbe18045d
openimis.policy.enabled=true
openimis.fhir.api.elig.policy.enabled=https://imislegacy.hib.gov.np/api/api_fhir/EligibilityRequest/
openimis.fhir.api.elig=https://imislegacy.hib.gov.np/api/api_fhir/EligibilityRequest/
openimis.fhir.api.claim=https://imislegacy.hib.gov.np/api/api_fhir/Claim/

openmrs.root.url=http://192.168.33.20:8050/openmrs/ws/rest/v1
openmrs.fhir.url=http://192.168.33.20:8050/openmrs/ws/fhir/Person
openmrs.user=admin
openmrs.password=test

openmrs.db.url=jdbc:mysql://localhost.localdomain/openmrs?user=dbuser&password=dbpassword
openelis.db.url=jdbc:mysql://localhost.localdomain/openmrs?user=dbuser&password=dbpassword

# HikariCP settings
# 60 sec
spring.datasource.hikari.connection-timeout=60000
# max 5